### ISSUE TITLE
Improve lip movement quality? 

### ISSUE THREAD

**Issue by SkalskiP** [s0md3v/roop#12]
Hi 👋🏻 

Is it possible to improve lip movement quality?

**Comment by s0md3v** [comment]
Unfortunately, I don't own the face-swapping model (`inswapper_128.onnx`) and have no idea how to improve it. It was published by insightface and then they took it down made it closed source so I doubt they will be improving it either.

I have been trying things since past week and I have been getting good enough results to publish this tool. You just need to make sure the face you have provided has more resolution and clarity than the face you are trying to replace. Under ideal conditions, the lips work well enough. Ideal here means a good angle and lighting.
