### ISSUE TITLE
[Feature] Automated post processing

### ISSUE THREAD

**Issue by Maki9009** [s0md3v/roop#146]
since the model outputs 128 quality its not really the best, but if its possible to have options to push the frames through DFDNET or CodeFormer for better quality outputs, 

DFDNET is pretty decent and re-taining the same person resemblance
CodeFormer is good but sometimes looses person resemblance 
GPEN is also decent maybe...

**Comment by FurkanGozukara** [comment]
I used codeformer in this tutorial

man it is taking huge processing time huge

34.) PC - Google Colab - Free

[**Mind-Blowing Deepfake Tutorial: Turn Anyone into Your Favorite Movie Star! PC & Google Colab - roop**](https://youtu.be/OI1LEN-SgLM)

[![image](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/4ce2ccf1-e5fd-4afd-a7ff-a8b65b69adc6)](https://youtu.be/OI1LEN-SgLM)

**Comment by henryruhs** [comment]
We would love automated post processing like in your video... this is one of our top priorities at the moment.

Pull requests and code ideas (to be posted here) are welcome.

**Comment by henryruhs** [comment]
It could be done via CodeFormer: https://github.com/sczhou/CodeFormer

Anyone up to send a PR? It needs to be optional via a checkbox.

**Comment by LeoLovechest** [comment]
If Codeformer is implemented please also add an adjustable weight slider with a default value of 0.7 

~ Inference

**Comment by Moeblack** [comment]
https://github.com/s0md3v/roop/pull/302
almost done. Just waiting for merging.

**Comment by janvarev** [comment]
@Moeblack Hi!
I've modified app.py file from codeformer package (inference_app call). Sorry, not tested. It may be included in roop as side stuff.

Now it allow you to pass img as cv2 image, and return result as cv2 image too (instead of file names in string). This allow to embed it directly in frame processing at 1 stage. There are 2 speed ups:
- Don't process frame if NO face here )
- Don't work with files (load, parse, save, move)

Also there are another speed up:
```
result = inference_app(
                    image=frame_path,
                    background_enhance=False,
                    face_upsample=True,
                    upscale=1,
                    codeformer_fidelity=0.7,
                )
```
This disable upscale and back enchance, but still increase face quality. Speed up is pretty significant.
[app.zip](https://github.com/s0md3v/roop/files/11645209/app.zip)

**Comment by henryruhs** [comment]
Early version using Codeformer landed in next branch

**Comment by matheusfterra** [comment]
> A versão inicial usando o Codeformer foi lançada na próxima ramificação

Hi, this made in this last update?

**Comment by henryruhs** [comment]
Yes but we ended up using GFPGAN as this worked better on multi threading.
