### ISSUE TITLE
Disk filling up

### ISSUE THREAD

**Issue by taladro** [s0md3v/roop#15]
On Windows 10 it consumed more than 30 gb from the main disk. 
I assume that is because of cache/scratch. I´m running it from a second disk and would love to be able to choose scratch folders location.

**Comment by s0md3v** [comment]
That's concerning. Are you trying to deepfake a very long video? How long is it?

**Comment by LokeYourC3PH** [comment]
Temporary solution: Download and install [Link Shell Extension](https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html).
Then, make a folder on your target drive (for the scratch directory), and name it something like "TEST" or "OUTPUT" (I'd use OUTPUT since the default name of all video outputs is just that, "OUTPUT.mp4"). Delete the original OUTPUT (or whatever) folder in your "roop" root directory. Then, right click on that folder on your scratch directory drive (OUTPUT), and choose "Pick Link Source". Then, go to your "roop" root directory, right click again, and choose "Drop As..." and then "Symbolic Link". From now on, don't rename any video and leave it as "OUTPUT.mp4". It will automatically create all the image files in that Symbolic Linked scratch directory on another drive, easy.

**Comment by taladro** [comment]
> That's concerning. Are you trying to deepfake a very long video? How long is it?

no, in fact it´s very short less than 2 minutes.
Afterwards I tried and chopped it to half.
Still the same problem.

**Comment by s0md3v** [comment]
@taladro with the latest patch, it will now save your frames in the directory you want your output.mp4 to be in.

**Comment by s0md3v** [comment]
I will later add chunked processing of bigger videos but let me take care of the urget things first.
