### ISSUE TITLE
A simple webui based on gradio

### ISSUE THREAD

**Issue by gonjay** [s0md3v/roop#269]
Here is sample code generated by ChatGPT4

```
# had to remove the code as this contained a unleashed version - next time you will be banned
```

**Comment by kool99988** [comment]
nice!!

**Comment by henryruhs** [comment]
we take a look into this and will probably merge it to the next branch. want was your actual prompt to chatgpt?

**Comment by helloasv** [comment]
good job.

**Comment by Diletant-001** [comment]
It works. Thx u

**Comment by davehornik** [comment]
@henryruhs 
I am literally testing the script only with nsfw vids/pics, since it's at least fun to look at them and easier to spot an error.

So, you are directly breaking your [AGPL-3.0 license](https://github.com/s0md3v/roop/blob/main/LICENSE) since "modifications" are allowed. I do not like this behaviour, threatening user for banning him for stuff he can do according to license.

**Comment by henryruhs** [comment]
From our disclaimer:

> To prevent misuse, it has a built-in check which prevents the program from working on inappropriate media.

What you do in your private machine is upon you, we are not the deepfake police

**Comment by henryruhs** [comment]
Merge with https://github.com/s0md3v/roop/issues/257

**Comment by davehornik** [comment]
@gonjay Check your gmail, thanks in advance.
