### ISSUE TITLE
Crash after upgraded

### ISSUE THREAD

**Issue by langyajiekou** [s0md3v/roop#296]
Just upgrade today using CPU mode and it will crash while the old version is working fine, what's the problem?

(Roop) PS F:\VSCode\roop-main> python run.py
F:\VSCode\roop-main\run.py:110: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
  img = img.resize((180, 180), Image.ANTIALIAS)
F:\VSCode\roop-main\run.py:128: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
  img = img.resize((180, 180), Image.ANTIALIAS)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Admin/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Admin/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Admin/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Admin/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Admin/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
F:\VSCode\Roop\lib\site-packages\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
  2%|██                                                                                                                 | 2/112 [00:02<02:12,  1.21s/it 17%|███████████████████▎                                                                                              | 19/112 [00:0 32%|████████████████████████████████████▋                                                                           49%|███████████████████████████████████████████████████████▉                                     66%|██████████████████████████████████████████████████████████████████████████ 82%|██████████████████████████████████████████████████████████████████████████ 96%|██████████████████████████████████████████████████████████████████████████100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 112/112 [00:03<00:00, 36.31it/s]
(Roop) PS F:\VSCode\roop-main>

**Comment by Coutinho159** [comment]
Probably due to the modifications inside the updated files. I also have a almost similar error showing this:

(Im using mac M1 pro)

i have the same issue but with extra error message error about multiprocessing on pool.pv and queues.pv:

It appeared this error message:

(myenv) name@MacBook-Pro-de-Bruno roop % python run.py --max-cores 2
2023-06-02 18:18:40.580 python[10350:18174948] +[CATransaction synchronize] called within transaction
2023-06-02 18:18:40.639 python[10350:18174948] +[CATransaction synchronize] called within transaction
/Users/name/roop/run.py:110: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
img = img.resize((180, 180), Image.ANTIALIAS)
2023-06-02 18:18:43.377 python[10350:18174948] +[CATransaction synchronize] called within transaction
2023-06-02 18:18:43.422 python[10350:18174948] +[CATransaction synchronize] called within transaction
/Users/name/roop/run.py:128: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
img = img.resize((180, 180), Image.ANTIALIAS)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/name/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/name/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/name/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/name/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/name/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
/Users/name/anaconda3/envs/myenv/lib/python3.9/site-packages/insightface/utils/transform.py:68: FutureWarning: rcond parameter will change to the default of machine precision times max(M, N) where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass rcond=None, to keep using the old, explicitly pass rcond=-1.
P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
100%|████████████████████████████████████████| 883/883 [00:01<00:00, 599.65it/s]
Exception ignored in: <function Pool.del at 0x17c8f85e0>
Traceback (most recent call last):
File "/Users/name/anaconda3/envs/myenv/lib/python3.9/multiprocessing/pool.py", line 268, in del
File "/Users/name/anaconda3/envs/myenv/lib/python3.9/multiprocessing/queues.py", line 371, in put
AttributeError: 'NoneType' object has no attribute 'dumps'

**Comment by henryruhs** [comment]
NSFW filter kicked in and you out :-)
