### ISSUE TITLE
AttributeError: 'INSwapper' object has no attribute 'taskname'

### ISSUE THREAD

**Issue by miserias21** [s0md3v/roop#42]
Hi!

I have this error when trying to execute "python3 run.py". To be more precise:

File "/.../lib/python3.10/site-packages/insightface/app/**face_analysis.py**", line 37, in __init__
    elif model.taskname not in self.models and (allowed_modules is None or model.taskname in allowed_modules):
AttributeError: 'INSwapper' object has no attribute 'taskname'

I am not experience with this kind of software, so maybe I am missing something obvious.

Thank you!

**Comment by thepvuguy** [comment]
I'm also experiencing this error.

**Comment by s0md3v** [comment]
Are you on windows? If yes, do you have Microsoft Visual C++ >14.0 installed?

**Comment by thepvuguy** [comment]
Yes, i have Microsoft Visual C++ >14.0 installed

**Comment by alimehdi242** [comment]
Hi I am experiencing the same issue any solution?

**Comment by alimehdi242** [comment]
@thepvuguy bro you got any solution I am stuck here

**Comment by alimehdi242** [comment]
@chenqiu1024 probably don't know

**Comment by chenqiu1024** [comment]
> I am experiencing the same thing. I guess it results in the inswapper_128.onnx file?

Because I encountered the 'inswapper_128.onnx not found' issue, then I found a solution and download the model file from the Mega link from here: https://github.com/s0md3v/roop/issues/20 . Then the model file can be found but I got this "'INSwapper' object has no attribute 'taskname'" at the constructor of class FaceAnalysis.
My console output:
`Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/domqiu/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/domqiu/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/domqiu/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/domqiu/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
`
The constructor of class FaceAnalysis:
`class FaceAnalysis:
    def __init__(self, name=DEFAULT_MP_NAME, root='~/.insightface', allowed_modules=None, **kwargs):
        onnxruntime.set_default_logger_severity(3)
        self.models = {}
        self.model_dir = ensure_available('models', name, root=root)
        onnx_files = glob.glob(osp.join(self.model_dir, '*.onnx'))
        onnx_files = sorted(onnx_files)
        for onnx_file in onnx_files:
            model = model_zoo.get_model(onnx_file, **kwargs)
            if model is None:
                print('model not recognized:', onnx_file)
            elif allowed_modules is not None and model.taskname not in allowed_modules:
                print('model ignore:', onnx_file, model.taskname)
                del model
            elif model.taskname not in self.models and (allowed_modules is None or model.taskname in allowed_modules):
                print('find model:', onnx_file, model.taskname, model.input_shape, model.input_mean, model.input_std)
                self.models[model.taskname] = model
            else:
                print('duplicated model task type, ignore:', onnx_file, model.taskname)
                del model
        assert 'detection' in self.models
        self.det_model = self.models['detection']
`
So is this a version mismatch issue? I just have no idea about what the inswapper model should be like.

**Comment by Feuer-Kampfer** [comment]
Same Issue as @chenqiu1024 here, I was getting `File "inswapper_128.onnx" does not exist!`

After I searched for the file and installed in `C:\Users\[USER]\.insightface\models\buffalo_l` I got a different error when running the script that says `elif model.taskname not in self.models and (allowed_modules is None or model.taskname in allowed_modules):
AttributeError: 'INSwapper' object has no attribute 'taskname'` Any idea how to fix?

**Comment by s0md3v** [comment]
@Feuer-Kampfer you should keep `inswapper_128.onnx` file in **roop** directory.

**Comment by alimehdi242** [comment]
@s0md3v I have the inswapper_128.onnx in the roop directory but still getting the same error, I have copied it in buffalo_l directory but still the same error

**Comment by jjandnn** [comment]
把模型inswapper_128.onnx放在roop文件夹中，不要在C:\Users\XX\.insightface\models\buffalo_l中同时存在。@alimehdi242 @zsxplace @all
Place the model inswapper_128.onnx in the root folder, not in C:\Users\XX\.insightface\models\buffalo_l.

**Comment by zsxplace** [comment]
thanks,it's work.

**Comment by zaazii** [comment]
It doesn't work for me. When I put it in the root folder it says inswapper_128 doesn't exist. When I put it in the buffalu folder it says 'INSwapper' object has no attribute 'taskname'.

**Comment by chenqiu1024** [comment]
> It doesn't work for me. When I put it in the root folder it says inswapper_128 doesn't exist. When I put it in the buffalu folder it says 'INSwapper' object has no attribute 'taskname'.

It's the root folder of roop, not that of insightface. I followed the instruction and not it works on my MacBookPro.

**Comment by qiukejk** [comment]
> It doesn't work for me. When I put it in the root folder it says inswapper_128 doesn't exist. When I put it in the buffalu folder it

thanks

**Comment by huanghaifeng98** [comment]
> remove buffalo_l , because maybe it is empty


![image](https://github.com/s0md3v/roop/assets/44279426/b3a50b67-5c3b-4e36-b2bb-52c817e10a39)
