### ISSUE TITLE
[Question] Why is the face added (it seems) with lower quality than the original?

### ISSUE THREAD

**Issue by flesler** [s0md3v/roop#456]
I consistently notice the replaced face is very pixelated. Even when the video resolution is much lower than the face photo, the quality of the new face is worse than the provided photo and also worse than the original face.

I know you guys, in the `next` branch allow changing the `pix_fmt`. But that's probably not it, because the video quality is fine, only the face is much lower quality

Is there something that can be done to increase this quality? I tried tweaking the `det_size`  but that didn't seem to do the trick

**Comment by ivancebellansanchez** [comment]
I'm no expert but it's because of inswapper_128.onnx, just as its name implies it renders faces at 128x128px, on a personal note, in the meantime you could run the exported frames by roop through codeformer on a local or remote stable diffusion instalation to upscale faces.
![test](https://github.com/s0md3v/roop/assets/37708320/06a84c4a-a01e-48a9-8bf5-0f4b58a71b03)

**Comment by flesler** [comment]
@ivancebellansanchez That could explain it. I do run them through GFPGAN, but that's much worse than getting actual high quality. Since the tool need to speculate and the face is changed in the process

**Comment by henryruhs** [comment]
Our next branch contains frame processors and supports an experimental face enhancer using codeformer.

**Comment by henryruhs** [comment]
Closed as topic has been is well explained.

**Comment by escoolioinglesias** [comment]
@henryruhs amazing the work you're doing! is there a set release day?
