### ISSUE TITLE
[NEXT] Only first job uses multiple threads

### ISSUE THREAD

**Issue by ZephyrusXI** [s0md3v/roop#468]
After launching with --gpu-threads=4 , only the first video uses 4 threads.
Subsequent videos only use a single thread.

![image](https://github.com/s0md3v/roop/assets/111444272/ac20023b-61d0-464d-8581-cc0879570f8a)

**Comment by henryruhs** [comment]
Enhancer is not ready and locked to 1 Thread.

**Comment by fortypercnt** [comment]
This problem is unrelated to the enhancer.
https://github.com/s0md3v/roop/blob/next/roop/core.py#L199-L200 overwrites execution_threads setting but they are not restored from user args. That only happens once at startup (https://github.com/s0md3v/roop/blob/next/roop/core.py#L71). If you process multiple times in the gui, this setting is gonna be wrong from the second time on.

**Comment by henryruhs** [comment]
now fixed in next
