### ISSUE TITLE
[Feature Request] Output default name from Face & Target VDO

### ISSUE THREAD

**Issue by Gardgio** [s0md3v/roop#485]
I like to try mix & match from multiple faces and target VDO which named for different people. It would be great if the default saving VDO name could be something as below example:

- Face: personA-Face1.jpg,
- Target VDO: VDO-A

Output file name: output-personA-Face1-VDO-A.mp4

**Comment by AlonDan** [comment]
I'm with you here,
I've already suggested a pretty dynamic way to handle it **[HERE - look at: 🟡 Auto Output](https://github.com/s0md3v/roop/issues/257)**

I hope it will be on the next branch, doing tests and naming our own outputs is annoying.

For example: In SimSwap it's much simple using suffix so it won't overwrite each other, and no need to name outputs manually (unless you want to).

**Comment by henryruhs** [comment]
Resolved via https://github.com/s0md3v/roop/commit/adc39879617ef07c9f40c9d0e1cdb9c737851077 and https://github.com/s0md3v/roop/commit/ee7dedf5b2745f4ef035d1e1b9d12eb4bc04719b

Submit a PR to improve normalize_output_path in the utilities if something is missing.

**Comment by AlonDan** [comment]
> Resolved via [adc3987](https://github.com/s0md3v/roop/commit/adc39879617ef07c9f40c9d0e1cdb9c737851077) and [ee7dedf](https://github.com/s0md3v/roop/commit/ee7dedf5b2745f4ef035d1e1b9d12eb4bc04719b)
> 
> Submit a PR to improve `normalize_output_path()` in the utilities if something is missing. Testing is welcome!

I'm trying to run it via the NEXT branch but I get this error:

`run.py: error: the following arguments are required: -f/--face, -t/--target, -o/--output`

Why do I need to type the file / paths manually... I should do that via the GUI and browse with the help of the buttons.

**Comment by henryruhs** [comment]
@AlonDan You are right, this broke the GUI... I changed it back

**Comment by AlonDan** [comment]
> @AlonDan You are right, this broke the GUI... I changed it back

Thanks I wasn't sure if I'm doing something wrong.

I'm trying the fixed you did few minutes ago
Now the GUI runs and when pressed the "Select a Face" for the first time I see on my Anaconda prompt this:
`warnings.warn(f"{type(self).__name__} Warning: Given image is not CTkImage but {type(image)}. Image can not be scaled on HighDPI displays, use CTkImage instead.\n")`

I'm not a programmer and I have no idea what it means, but I didn't have this message on the version before.

I notice something about HighDPI - I can tell you that the FONT is very small on my 2K monitor (using 100% DPI scale on windows) it will probably be impossible to read on 2.5K and 4K res.

Another thing I noticed, I use the exact same command I used before (with my limited GPU 4GB VRAM and the PC itself with 32GB RAM)
and the process is extremely slow now, like it's not even using the GPU... I got 1.36s/frame, maybe this will help:

```
Processing: 100%|████████████████████████████████████| 22/22 [00:29<00:00,  1.35s/frame, execution_providers=['CPUExecutionProvider'], threads=8, memory=24]
Status: Detecting fps...
Status: Creating video with 30.0 fps...
```

I'm looking on the new commands and I guess that what I used for the GPU is not there anymore, probably it's something else now so that's why it's not using my GPU.

Also it uses 8 threads... I can't use more than 2-3 without getting out of memory so I use 2... but I think all the commands are now changed I'm still reading to see if I understand what changed to what based on the description, still can't figure out the GPU one, I see CPU related execution... I'm a bit confused, sorry it's on me, I'm still a noob so it's not a complain I'm just giving feedback on the very last NEXT branch in case it helps ;)

This is the last version command I used that works wonderful, and faster:
`python run.py --gpu-vendor nvidia --max-memory 24 --gpu-threads=2`
