### ISSUE TITLE
GPU takes longer than CPU

### ISSUE THREAD

**Issue by adam-andrzejczak** [s0md3v/roop#50]
I did a test on a 10 seconds clip. The result is the same in terms of quality, but on CPU it took 4 minutes, while on GPU it took 5 minutes.
CPU: Ryzen 5900x
GPU: 3080 RTX
64 gb RAM

Both logs says sth about "Applied providers: ['CPUExecutionProvider']"

Is it something on the project side on my side?

**Comment by s0md3v** [comment]
This is a known issue. Not with this tool but the library we use to interact with GPU/CPU.

Someone apparently solved this issue ([source](https://github.com/s0md3v/roop/issues/2#issuecomment-1567565942)) and they will publish a fix soon.

I will now close this issue because it's a duplicate but stay tuned!

PS: How is a 10 sec clip taking 4 minutes on your CPU? It has 12 cores right? Can you quickly check if they are being used while you run this program?
