### ISSUE TITLE
Followed instructions but no GPU utilization

### ISSUE THREAD

**Issue by bbecausereasonss** [s0md3v/roop#70]
In WSL Ubuntu, no GPU utilization.... Are we missing install instructions? Should I be installing Pytorch?

**Comment by ZeroCool22** [comment]
> In WSL Ubuntu, no GPU utilization.... Are we missing install instructions? Should I be installing Pytorch?

Yeah, it needs a proper guide video, a lot of ppl having problems with the GPU usage...

**Comment by LokeYourC3PH** [comment]
> > In WSL Ubuntu, no GPU utilization.... Are we missing install instructions? Should I be installing Pytorch?
> 
> Yeah, it needs a proper guide video, a lot of ppl having problems with the GPU usage...

The issue seems to be that many people have different versions of stuff installed all across the board, while the software only works with a very limited set of versions at hand. Some have old drivers, some have the newest, some have PyTorch, some don't, some TensorRT or cuDNN, some don't, and those who have, have varying versions across the board.

It would be better to make a unified installation command that installs the exactly required software and drivers across the board, which is where the issue seems to be.

**Comment by TitasDas** [comment]
> > > In WSL Ubuntu, no GPU utilization.... Are we missing install instructions? Should I be installing Pytorch?
> > 
> > 
> > Yeah, it needs a proper guide video, a lot of ppl having problems with the GPU usage...
> 
> The issue seems to be that many people have different versions of stuff installed all across the board, while the software only works with a very limited set of versions at hand. Some have old drivers, some have the newest, some have PyTorch, some don't, some TensorRT or cuDNN, some don't, and those who have, have varying versions across the board.
> 
> It would be better to make a unified installation command that installs the exactly required software and drivers across the board, which is where the issue seems to be.

Is the purpose solved temporarily if we mentioned the latest versions of all the required tools - for example in response to this when it comes to the libraries used now we have frozen them at specific versions. Are you suggesting we do something similar here? would that help?

**Comment by LokeYourC3PH** [comment]
> > > > In WSL Ubuntu, no GPU utilization.... Are we missing install instructions? Should I be installing Pytorch?
> > > 
> > > 
> > > Yeah, it needs a proper guide video, a lot of ppl having problems with the GPU usage...
> > 
> > 
> > The issue seems to be that many people have different versions of stuff installed all across the board, while the software only works with a very limited set of versions at hand. Some have old drivers, some have the newest, some have PyTorch, some don't, some TensorRT or cuDNN, some don't, and those who have, have varying versions across the board.
> > It would be better to make a unified installation command that installs the exactly required software and drivers across the board, which is where the issue seems to be.
> 
> Is the purpose solved temporarily if we mentioned the latest versions of all the required tools - for example in response to this when it comes to the libraries used now we have frozen them at specific versions. Are you suggesting we do something similar here? would that help?

Yes that's exactly what I am suggesting. A working set of all required software and drivers has to be found across the board, and be set as standard. You can have the latest NVIDIA or AMD drivers, but since "torch" is a requirement, that specific torch version + CUDA should be downloaded and installed. CUDA can be installed and/or downloaded locally into the roop "core" dir (or wherever) rather than using the system available one, avoiding that the system is using a too new or too old version. This can be done for all required tools actually, and then for each OS this can be limited to only install what is required for said OS to avoid someone downloading the libraries and drivers of say Mac and Linux if they are on Windows, or vice versa, when they don't need those.

**Comment by henryruhs** [comment]
Related https://github.com/s0md3v/roop/issues/88

**Comment by henryruhs** [comment]
Join Discord for instant help
