### ISSUE TITLE
Bad at coding, confused of how to install

### ISSUE THREAD

**Issue by FruitPunchMan** [s0md3v/roop#78]
When you say "run the following commands in terminal" what terminal am I supposed to be putting it into?

**Comment by OgSamu** [comment]
depends on your system, but on windows: use the command line (cmd) which is the default, if you are on a Unix-like Systems like (Linux, macOS, BSD) then you would use Bash which is the default terminal on most Unix-like systems.

**Comment by FruitPunchMan** [comment]
I am on windows, what should I be putting in the command prompt?

**Comment by LokeYourC3PH** [comment]
Not to discourage you, but I don't think this project is exactly made or cut out for you. I'm not terrific at programming either (not coding, programming, coding is fairly easy), but I know my way around systems and terminals.

Knowing how to use a terminal is one of the most core aspects of a system you can get to. If you do not know how to do that, start with that first. Otherwise you will be heavily overwhelmed even if you "follow" the instructions on the front page. Many things are omitted there because it is assumed that anyone using it, has enough knowledge to fill most of the gaps themselves (with varying degrees of success and knowledge). Not even knowing how to use a terminal is absolutely going to make you feel overwhelmed, and is also outside the scope of this project.

Look up some tutorials on how to do that, we all had to start there, so it would be a good time for you to do so now.

**Comment by LokeYourC3PH** [comment]
Here, you should start with this as your core foundation:
https://www.freecodecamp.org/news/command-line-for-beginners/
https://www.makeuseof.com/tag/a-beginners-guide-to-the-windows-command-line/
https://brainlix.com/computer-terminology/
https://docs.python.org/3/using/cmdline.html
https://www.digitalcitizen.life/command-prompt-how-use-basic-commands/
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Command_line

**Comment by LokeYourC3PH** [comment]
As you are on Windows as well, you'd be better fit for now to install WSL 2 and setup Ubuntu 22.04 LTS (I hope you're on Windows 10 or 11). With that, you can practice the Linux Terminal right away, in which you'll learn the most. You can apply the knowledge learned there to other systems later, but Linux might be the easiest for now as there's plenty more tutorials for it than Windows or Mac. If you use WSL 2 to install Ubuntu to run on your system, you can directly interface with Ubuntu on your Windows PC which is neat af, and can then learn how to use a terminal that way too.

**Comment by LokeYourC3PH** [comment]
@s0md3v You can close this issue, it's completely irrelevant to this project.
