### ISSUE TITLE
Only close face video working..

### ISSUE THREAD

**Issue by daarkwulf** [s0md3v/roop#797]
Sorry to trouble u my lord...something I have to tell u if anything wrong u find plz guide me..so I was just experimenting since 2 weeks 
Tried multiple fps from 20 to 30
Codec and more and found that only few stuff working ...may be it's only on my system 
Windows 10
Only cpu is working
Have amd graphic but not taking by roop.

First the video has to be not more than 1.5 min
The face should to be close like passport face in the whole video otherwise  roop stops after extracting frames
Also I saw that when I crop the input face till nose and not showing lips then only it was able to process gud quality output otherwise it was showing and covering  lips of target person  even when the person in video is touching lips with his hands and then anyone can clearly tell u that this is low level editing..

Lastly the output video havin lower quality face swap than original video. So it's mismatching the quality of video vs quality of face morphed.

Perhaps u are already working on that...
Nowplz tell me lord.. is it with mine system or is it normal to everyone..plus can u guide me how to add amd graphic working with roop..any link..any tutorial would be thankful as m new to this python so don't know how to add commands and where..
And if I have to use command way to add amd ..so should I do it on conda env or should  I install python and then do something ??
Coz I got some video telling onxruntime rcom installing way by command but m not able to find where to add it.. 

Thanx for roop
Thanx for hearing
Thanx for help
Keep working we all love u. 
Will donate soon..

**Comment by henryruhs** [comment]
You come up with 5 different issues in one... I try to give you a general answer: roop is just a runner using third party models, everything that is related to the limitations of such models is not in our hands. Such as low quality output as of the 128 inswapper and clipping issues.

Since roop 1.2.0 there is a face recognition to support multiple faces in a video, this comes with drawbacks of course as we need to create a face reference. Read more: https://github.com/s0md3v/roop/wiki/Understand-the-face-vocabulary

AMD is not official supported by the onnxruntimes, you can compile it under Linux - but that is for VERY advanced users only.
